parameters:
#    assignatura.example.class: Gesnotes\AssignaturaBundle\Example

services:
#    assignatura.example:
#        class: %assignatura.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
