parameters:
#    alumne.example.class: Gesnotes\AlumneBundle\Example

services:
#    alumne.example:
#        class: %alumne.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
